yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор поста',
        on_delete=models.CASCADE,
    )
    group = models.ForeignKey(
        'Group',
        related_name='posts',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:10]


class Group(models.Model):
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200,
        unique=True,
    )
    slug = models.SlugField(
        verbose_name='Ссылка группы',
        max_length=200,
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание группы',
    )

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    posts = Post.objects.all()[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="icon" href="img/fav/fav.ico" type="image">
      <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/fav/favicon-32x32.png" %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
      <meta name="msapplication-TileColor" content="#000">
      <meta name="theme-color" content="#ffffff">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <title>
      {% block title %} {% endblock %}
      </title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main> 
      {% block content %}
        Контент не подвезли 
      {% endblock %}
    </main>       
    <footer>
        {% include 'includes/footer.html' %}   
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube</a>
      </div>
    </nav>      
  </header>


  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}пример{% endblock %}
{% load static %}
    {% block content %} 
      <div class="container py-5">     
      <h1>{{ group.title }}</h1> 
      <p>{{ group.description }}</p>
        <article>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>    
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
      </div>
    {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}пример{% endblock %}
{% block content %}
      <div class="container py-5">     
        <h1>Последниее обновление на сайте</h1>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          <p>
            {{ post.text }}
          </p>
          {% if post.group %} 
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %} 
          {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}